// <auto-generated />
namespace WMS.Server.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class testMysql : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(testMysql));
        
        string IMigrationMetadata.Id
        {
            get { return "201602140901018_testMysql"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
